### PR TITLE
Refactor release CI

### PR DESCRIPTION
**Pull request by syndr**
Image tags will be generated based upon the event that triggered the workflow:
  - `push` event:
    - main branch: `latest`
    - devel branch: `devel`
    - all other branches: `<branch name>-latest`
  - `pull_request` event: `DEV-PR-<pull_request_number>`
    - Branches must be added to the on.pull_request.branches array above to trigger
  - `release` event: `<tag_name>`
  - `schedule` event: `nightly`
    -  This will be the same configuration as the `latest` tag, but may contain updated packages, etc. from upstream
  - all other events: `<first 7 chars of commit sha>`

Run podman test as part of same workflow as release (fail faster)

### CODE REVIEW

**Comment by emoruzzi** [comment]
Do we need to schedule nightly, or is that something we can do weekly?

**Comment by emoruzzi** [comment]
We may want to consider using something like `if: github.event.review.state == 'approved'` since this is public too

**Comment by syndr** [comment]
> Do we need to schedule nightly, or is that something we can do weekly?

Weekly would probably be plenty -- I can do that.

**Comment by emoruzzi** [comment]
> We may want to consider using something like `if: github.event.review.state == 'approved'` since this is public too

Managed this via  action settings

**Pull request merged**
